language: node_js
node_js:
  - '8.5'
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run package-mac && tar -zcf releases/mac.tar.gz releases/bitva-game-darwin-x64
deploy:
  provider: releases
  api_key:
    secure: "Efq8ErKcSQ97ZAflDsJyAgk+PC6t7x4VBtgq6DC1aRm4T9oMni0YZEu9GD/xQMtV83oCY6y86yC95wUR9+PkeeUWO7S5n8wksI0MVzEhIbK/dOMq9T2sbR4cpcoX06Bfv/epHt9TUzYtNRIfey3Rbzzc7UJew/X52Gz3n119Go4Coxzx/5SjgqwBSZubUPuPt6e2x1Ntb6R+y5xVOv3+gNj7u4l2g2vN/W48MERNFBcBJHPTYIHRIppKGTy3XfoKXWM2LvXdGLY4HpAMKmx5tWBasNaQ1M5hPvdVu2/76TcVipwvqqFGlA+Ait56N1pU5Tex1tYfZnLikBWYJ7avCCJUf/+kPxPfRg3tCWM3hq2JLa+yPJloFDwcIQmbEfjPbP6FF4yO2RnK7i0TZYM5qMoA5pepV9VMfohbMGG+xD/afj5gIHgidch9fyBcf+Ez9NEOXGGVbq0ArxW4cU58GaJFkN5dtoXJRz7LNX1ARonAAe7f77zXO7YCtJxjws5KEdQwv+I8oVQQEshl/gFJ++nBWSXRz7HMvhDvfOPBAPSmHEpqEA8mIyvKfwix9drKoyVtgfi2Y3VnnMked0+mq/S8LQnpXYq5/mkSZruvJ88qvB0hRR6BxAhQ7JjbeeaJQLXuXzO/CV3XKEH4vrl8u2Ax1GvZLno5r8+kGRQcI6U="
  file: 
    - releases/mac.tar.gz
  skip_cleanup: true
  on:
    repo: BITVA-Game/bitva-game
    branch: buildTest
