const STARTSCREEN = 'STARTSCREEN';
const PROFILE = 'PROFILE';
const PLAY = 'PLAY';
const NETWORKPLAY = 'NETWORKPLAY';
const INIT = 'INIT';
const HEROSELECTED = 'HEROSELECTED';
const HEROSELECT = 'HEROSELECT';
const DEALALL = 'DEALALL';
const ACTION = 'ACTION';
const GAMESCREEN = 'GAMESCREEN';
const VERSUS = 'VERSUS';

module.exports = {
    STARTSCREEN,
    PROFILE,
    PLAY,
    NETWORKPLAY,
    HEROSELECT,
    INIT,
    HEROSELECTED,
    DEALALL,
    ACTION,
    GAMESCREEN,
    VERSUS,
};
